### PR TITLE
Add ci for test

### PR DESCRIPTION
**Pull request by rodrigomelo9**
This PR adds CI for building and testing vhd2vl on each push. It also documents the dependencies required for these actions.

### CODE REVIEW

**Comment by ldoolitt** [comment]
Again, I basically like it.

Two small things:
> runs-on: ubuntu-latest

My preference is always to freeze the software-supply-chain for CI,  Could this be changed to "ubuntu-numbat" or "debian-bookworm" or something?  When a new OS comes out, I'd like to choose it explicitly, instead of having something fail mysteriously when we change something unrelated.

> run: make -j$(nproc)

nproc appears to not be defined.  Can this just say "make"? Compared to a lot of other CI on github, this thing is super-quick.

**Comment by ldoolitt** [comment]
Other random comments:

sudo in a containerized context feels bizarre. I suppose it's correct here.

This action gives some 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Can you swap in apt-get instead of apt?

Other than that, it does look very good.  Adding CI is fantastic in general.
I also like how short and easy-to-read test.yml is in this case.  :-)

**Comment by rodrigomelo9** [comment]
I replaced ubuntu-latest with the currently supported fixed versions.
Without sudo,  'apt' fails and 'install' issues a warning.
I applied other suggestions.

**Comment by ldoolitt** [comment]
Looks good!  Yes, I want to squash this one.  I'm out of time for now, so maybe later today.

**Pull request merged**
